In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_excel('qqq.xlsx')
df = df.loc[df['Volume']==0.3]
df.head()

,Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Time2,Price3,Commission,Swap,Profit,Column14,Column15
32,2022.01.18 01:01:13,6351324,AUDCHF,sell,0.3,0.65877,0.66272,0.65679,2022.01.19 06:33:15,0.65937,0,-1.18,-19.65,NaN,NaN
33,2022.01.18 01:01:35,6351327,EURNZD,sell,0.3,1.67832,1.68839,1.67329,2022.01.18 21:39:29,1.67329,0,0.00,102.25,NaN,NaN
34,2022.01.18 01:01:49,6351328,NZDJPY,sell,0.3,77.86800,78.33500,77.63400,2022.01.18 10:46:22,77.63400,0,0.00,61.21,NaN,NaN
35,2022.01.18 04:01:48,6352527,GBPCHF,sell,0.3,1.24738,1.25486,1.24364,2022.01.18 14:48:56,1.24364,0,0.00,122.73,NaN,NaN
36,2022.01.18 05:01:50,6353143,GBPJPY,buy,0.3,156.69500,155.71300,157.12300,2022.01.18 15:00:06,155.71100,0,0.00,-257.49,NaN,NaN

In [8]:
ag = df.groupby('Symbol').agg({'Profit':np.sum, 'Time':np.size}).rename({'Time':'Count'}).reset_index()
ag.sort_values('Profit')

    Symbol  Profit  Time
0   AUDCHF -693.17    14
6   EURAUD -224.99     1
15  NZDCAD -123.01     1
5   CHFJPY    3.54     9
13  GBPCHF   13.62     2
20  USDJPY   40.51     2
2   AUDUSD   53.70     2
10  EURNZD  102.25     1
8   EURGBP  103.11     1
12  GBPAUD  126.23     4
3   CADCHF  141.21    13
4   CADJPY  144.96     2
11  EURUSD  162.30     3
18  NZDUSD  188.10     5
7   EURCHF  308.47     3
9   EURJPY  308.86     3
19  USDCHF  318.69     8
1   AUDJPY  394.11    12
14  GBPJPY  482.40     7
16  NZDCHF  486.24    10
17  NZDJPY  551.52     9

In [10]:
df[df['Symbol']=='AUDCHF']

,Time,Position,Symbol,Type,Volume,Price,S / L,T / P,Time2,Price3,Commission,Swap,Profit,Column14,Column15
32,2022.01.18 01:01:13,6351324,AUDCHF,sell,0.3,0.65877,0.66272,0.65679,2022.01.19 06:33:15,0.65937,0,-1.18,-19.65,NaN,NaN
37,2022.01.18 06:01:13,6354500,AUDCHF,sell,0.3,0.65797,0.66195,0.65603,2022.01.19 08:42:57,0.65892,0,-1.18,-31.12,NaN,NaN
44,2022.01.18 08:01:13,6355843,AUDCHF,sell,0.3,0.65841,0.66236,0.65643,2022.01.19 08:43:50,0.65896,0,-1.18,-18.02,NaN,NaN
64,2022.01.18 20:01:14,6376392,AUDCHF,sell,0.3,0.65814,0.66209,0.65617,2022.01.19 15:57:33,0.66209,0,-1.18,-129.33,NaN,NaN
69,2022.01.19 01:01:14,6381000,AUDCHF,sell,0.3,0.65883,0.66278,0.65685,2022.01.19 16:29:38,0.66279,0,0.00,-129.62,NaN,NaN
71,2022.01.19 03:01:15,6381701,AUDCHF,sell,0.3,0.65895,0.66290,0.65697,2022.01.19 16:34:13,0.66290,0,0.00,-129.25,NaN,NaN
72,2022.01.19 07:01:20,6382964,AUDCHF,sell,0.3,0.65810,0.66205,0.65613,2022.01.19 15:57:19,0.66205,0,0.00,-129.33,NaN,NaN
75,2022.01.19 11:01:15,6386336,AUDCHF,sell,0.3,0.65807,0.66202,0.65610,2022.01.19 15:57:19,0.66202,0,0.00,-129.33,NaN,NaN
77,2022.01.19 12:01:15,6387599,AUDCHF,sell,0.3,0.65942,0.66338,0.65744,2022.01.20 03:17:14,0.66339,0,-3.53,-130.24,NaN,NaN
79,2022.01.19 18:01:16,6397292,AUDCHF,sell,0.3,0.66138,0.66535,0.65940,2022.01.20 17:01:14,0.66468,0,-3.53,-108.21,NaN,NaN
116,2022.01.21 03:01:18,6463210,AUDCHF,sell,0.3,0.65978,0.66374,0.65780,2022.01.21 05:39:21,0.65780,0,0.00,64.92,NaN,NaN
121,2022.01.21 04:01:19,6468267,AUDCHF,sell,0.3,0.65943,0.66339,0.65745,2022.01.21 10:17:17,0.65741,0,0.00,66.27,NaN,NaN
129,2022.01.21 05:01:18,6473964,AUDCHF,sell,0.3,0.65866,0.66261,0.65668,2022.01.21 11:08:35,0.65668,0,0.00,65.02,NaN,NaN
136,2022.01.21 06:01:18,6480220,AUDCHF,sell,0.3,0.65829,0.66224,0.65632,2022.01.21 11:13:14,0.65632,0,0.00,64.72,NaN,NaN